"""Resource setup module for Fork Lift application.

This module initializes all runtime resources including:
- Serial communication for hardware control
- MQTT configuration for remote control
- Camera calibration and AprilTag detection
- Camera capture interface

All resources are initialized gracefully - missing dependencies will not cause
the application to fail, allowing the system to run in degraded mode.
"""
import os
import time
import logging
from pathlib import Path
import numpy as np
from dotenv import load_dotenv

logger = logging.getLogger(__name__)


def setup_resources(base_dir: str | None = None):
    """Initialize and return runtime resources as a dict.

    This function attempts to initialize all required resources for the fork lift
    application. Each resource is optional - if a resource cannot be initialized
    (e.g., camera not available, calibration files missing), it will be set to None
    and the application will continue to run in a degraded mode.

    Args:
        base_dir (str | None): Base directory for loading calibration files.
            If None, uses the parent directory of this file.

    Returns:
        dict: A dictionary containing the following keys:
            - ser (serial.Serial | None): Serial port for hardware communication
            - mqtt_username (str | None): MQTT broker username from environment
            - mqtt_password (str | None): MQTT broker password from environment
            - mqtt_host (str | None): MQTT broker hostname from environment
            - mqtt_port (int | None): MQTT broker port from environment
            - web_socket_url (str | None): WebSocket server URL from environment
            - camera_matrix (np.ndarray): 3x3 camera intrinsic matrix
            - dist_coeffs (np.ndarray): Distortion coefficients (5 elements)
            - camera_params (tuple): (fx, fy, cx, cy) camera parameters
            - tag_size (float): AprilTag size in meters (default 0.05)
            - at_detector (Detector | None): AprilTag detector instance
            - cap (cv2.VideoCapture | None): Camera capture object
    """
    # Try serial connection (non-fatal)
    # Attempts to open serial port at /dev/ttyACM0 with 115200 baud rate
    # This is typically used for Arduino or STM32 microcontroller boards
    ser = None
    try:
        import serial
        ser = serial.Serial("/dev/ttyACM0", 115200, timeout=1)
        logger.info("Serial connection established")
    except Exception as e:
        logger.debug(f"Serial connection not available: {e}")
        ser = None

    # small delay to let serial initialize if present
    if ser:
        time.sleep(2)

    # Load environment variables from .env file if present
    # Allows configuration without hardcoding secrets or connection details
    load_dotenv()

    # Load MQTT configuration from environment variables
    # These can be set in a .env file or as system environment variables
    mqtt_username = os.getenv("MQTT_USERNAME")
    mqtt_password = os.getenv("MQTT_PASSWORD")
    mqtt_host = os.getenv("MQTT_HOST")
    mqtt_port = int(os.getenv("MQTT_PORT")) if os.getenv("MQTT_PORT") else None
    web_socket_url = os.getenv("WEB_SOCKET_URL")

    # Resolve base directory for loading calibration files
    # Uses either the provided path or the package parent directory
    if base_dir:
        base = Path(base_dir)
    else:
        base = Path(__file__).resolve().parent.parent

    # Load camera calibration matrices (non-fatal)
    # These are stored as numpy files generated by camera calibration scripts
    # If not available, use default dummy values for testing/demo purposes
    camera_matrix = None
    dist_coeffs = None
    camera_params = None
    
    try:
        camera_matrix = np.load(str(base / "camera_calibration" / "camera_matrix.npy"))
        dist_coeffs = np.load(str(base / "camera_calibration" / "dist_coeffs.npy"))
        camera_params = (
            camera_matrix[0, 0],
            camera_matrix[1, 1],
            camera_matrix[0, 2],
            camera_matrix[1, 2],
        )
        logger.info("Camera calibration loaded")
    except Exception as e:
        logger.debug(f"Camera calibration files not available: {e}")
        # Set default dummy calibration values for testing without real camera
        camera_matrix = np.eye(3)
        dist_coeffs = np.zeros(5)
        camera_params = (800.0, 800.0, 320.0, 240.0)  # Default focal length and principal point

    tag_size = 0.05

    # Load AprilTag detector (non-fatal)
    # Uses the pupil_apriltags library for detecting AprilTags in images
    # Configuration parameters are tuned for the specific use case
    at_detector = None
    try:
        from pupil_apriltags import Detector
        at_detector = Detector(
            families="tag25h9",
            nthreads=1,
            quad_decimate=1.0,
            quad_sigma=0.0,
            refine_edges=1,
            decode_sharpening=0.25,
            debug=0,
        )
        logger.info("AprilTag detector initialized")
    except Exception as e:
        logger.debug(f"AprilTag detector not available: {e}")
        at_detector = None

    # Try camera connection (non-fatal)
    # Opens the default camera (index 0) using OpenCV
    # Returns None if camera is not available or not accessible
    cap = None
    try:
        import cv2
        cap = cv2.VideoCapture(0, cv2.CAP_V4L2)  # Use V4L2 backend for Raspberry Pi
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, 320) # lower resolution for faster processing
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 240)
        cap.set(cv2.CAP_PROP_BUFFERSIZE, 1) # Set buffer size to 1 to reduce latency
        cap.set(cv2.CAP_PROP_FPS, 15)
        if not cap.isOpened():
            logger.debug("Camera not available")
            cap = None
        else:
            logger.info("Camera initialized")
    except Exception as e:
        logger.debug(f"Camera not available: {e}")
        cap = None

    return {
        "ser": ser,
        "mqtt_username": mqtt_username,
        "mqtt_password": mqtt_password,
        "mqtt_host": mqtt_host,
        "mqtt_port": mqtt_port,
        "web_socket_url": web_socket_url,
        "camera_matrix": camera_matrix,
        "dist_coeffs": dist_coeffs,
        "camera_params": camera_params,
        "tag_size": tag_size,
        "at_detector": at_detector,
        "cap": cap,
    }